import Footer from './components/footer'
import Navbar from './components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/header.js';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <main className={inter.className}>
                <Header />
                <Navbar />
                {children}
                <Footer />
            </main>
        </html>
    )
}
